from weapons import *
from game_objects import *
from random import randint

player_jake = {
    'name': 'Jake',
    'body state': {
        'viewing range': 600,
        'regeneration ability': 0.001,
        'blood volume': 15000,
        'max blood volume': 15000,
        'marksmanship': 100,  # The higher -- the better
        'blood volume replenish': .01,
        'stamina replenish': 1,
        'consciousness replenish': 10,
        'bleeding reduce': .01,  #

        'bleeding resistance': 0,  # Reduce bleeding, in percents.
        'pain resistance': 1,  # Change total pain level by multiplying total pain level to this number.
                               # Below 1 is reducing, above 1 is increasing. The smaller the number, the stronger pain resistance.
                               # Zero means total pain resist.
        # 'max stamina default': 12200,
        'max stamina': 120,
        'max fatigue': 100,
        'max consciousness': 1000,
        'consciousness threshold': 10,
        'luck': 5,
        'strength': 25,
        'weight': 70,  # Kilos.
        'reflexes': 230,  # minimal threshold of event speed which creature able to notice (in ms)
        'default reflexes': 230,
    },
    'body': {
        'head': {
            'hardness': 100
        },
    },
    'action points': 100,
    'max speed': .4,
    'reflexes': randint(100, 150),
    'uses light source': False,
    'items': (SMP_9mm,pistol_9mm,chi_punch,pistol_9mm_ammo,shotgun,shotgun_ammo,flashlight,kitchen_knife,claw,knuckles,tiny_heal_vial,painkillers),
    'avatar': 'Jake',
    'animations': {
        'firearm attack':
            {
            'right': {'repeat': False, 'interruptable': False, 'sequence': (4,4,5,5,4,4,4,4,4), 'speed': 1,
           'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
           'left': {'repeat': False, 'interruptable': False, 'sequence': (4,4,5,5,4,4,4,4,4), 'speed': 1,
           'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
           'up': {'repeat': False, 'interruptable': False, 'sequence': (7,7,7,7,7,7,7,7,7), 'speed': 1,
           'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
           'down': {'repeat': False, 'interruptable': False, 'sequence': (6,6,6,6,6,6,6,6,6), 'speed': 1,
           'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
           },
        'SMP attack': {
            'right': {'repeat': False, 'interruptable': False, 'sequence': (4, 4, 5, 5, 4, 5,5, 4, 5,5, 4, 4, 4), 'speed': 1,
                                     'sound': 'gunshot', 'sound at frames': (2,5,8), 'repeat from frame': 0},
                           'left': {'repeat': False, 'interruptable': False, 'sequence': (4, 4, 5, 5, 4, 5,5, 4, 5,5, 4, 4, 4), 'speed': 1,
                                    'sound': 'gunshot', 'sound at frames': (2,5,8), 'repeat from frame': 0},
                           'up': {'repeat': False, 'interruptable': False, 'sequence': (7, 7, 7, 7, 7, 7, 7, 7, 7,7,7,7,7), 'speed': 1,
                                  'sound': 'gunshot', 'sound at frames': (2,5,8), 'repeat from frame': 0},
                           'down': {'repeat': False, 'interruptable': False, 'sequence': (6, 6, 6, 6, 6, 6, 6, 6, 6,6,6,), 'speed': 1,
                                    'sound': 'gunshot', 'sound at frames': (2,5,8), 'repeat from frame': 0},
                           },
        'shotgun attack': {
            'right': {'repeat': False, 'interruptable': False, 'sequence': (4,4,5,5,4,4,4,4,4), 'speed': 1,
                      'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
            'left': {'repeat': False, 'interruptable': False, 'sequence': (4,4,5,5,4,4,4,4,4), 'speed': 1,
                      'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
            'up': {'repeat': False, 'interruptable': False, 'sequence': (7,7,7,7,7,7,7,7,7), 'speed': 1,
                      'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
            'down': {'repeat': False, 'interruptable': False, 'sequence': (6,6,6,6,6,6,6,6,6), 'speed': 1,
                      'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
        },
        'melee attack': {
            'right': {'repeat': False, 'interruptable': False, 'sequence': (32,33,33,33), 'speed': 1,
                      'sound': 'swing', 'sound at frames': (1,), 'repeat from frame': 0},

            'left': {'repeat': False, 'interruptable': False, 'sequence': (32,33,33,33), 'speed': 1,
                      'sound': 'swing', 'sound at frames': (1,), 'repeat from frame': 0},
            'up': {'repeat': False, 'interruptable': False, 'sequence': (7,7,7,7), 'speed': 1,
                      'sound': 'swing', 'sound at frames': (1,), 'repeat from frame': 0},
            'down': {'repeat': False, 'interruptable': False, 'sequence': (6,6,6,6), 'speed': 1,
                      'sound': 'swing', 'sound at frames': (1,), 'repeat from frame': 0},
        },
        'get hurt': {
            'right': {'repeat': False, 'interruptable': False, 'sequence': (12,13,12,13,12,13,12,13), 'speed': 2,
                     'sound': 'jake groan', 'sound at frames': (1,), 'repeat from frame': 0},
            'left': {'repeat': False, 'interruptable': False, 'sequence': (12,13,12,13,12,13,12,13), 'speed': 2,
                     'sound': 'jake groan', 'sound at frames': (1,), 'repeat from frame': 0},
            'up': {'repeat': False, 'interruptable': False, 'sequence': (7,13,7,13,7,13,7,13), 'speed': 2,
                     'sound': 'jake groan', 'sound at frames': (1,), 'repeat from frame': 0},
            'down': {'repeat': False, 'interruptable': False, 'sequence': (27,13,27,13,27,13,27,13), 'speed': 2,
                     'sound': 'jake groan', 'sound at frames': (1,), 'repeat from frame': 0},
        },
        'be dead': {
            'right': {'repeat': True, 'interruptable': True, 'sequence': (40,), 'speed': 1,
                    'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (40,), 'speed': 1,
                    'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (40,), 'speed': 1,
                    'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (40,), 'speed': 1,
                    'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
        },
        'head explode': {
            'right': {'repeat': True, 'interruptable': True, 'sequence': (34, 35, 36, 37, 38, 39, 40), 'speed': 1,
                         'sound': None, 'sound at frames': (0,), 'repeat from frame': 6},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (34, 35, 36, 37, 38, 39, 40), 'speed': 1,
                         'sound': None, 'sound at frames': (0,), 'repeat from frame': 6},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (34, 35, 36, 37, 38, 39, 40), 'speed': 1,
                         'sound': None, 'sound at frames': (0,), 'repeat from frame': 6},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (34, 35, 36, 37, 38, 39, 40), 'speed': 1,
                         'sound': None, 'sound at frames': (0,), 'repeat from frame': 6},
        },
        'lay down': {
            'right': {'repeat': True, 'interruptable': True, 'sequence': (27,27,28,28,29,30,30,31), 'speed': 2,
                     'sound': None, 'sound at frames': (3,), 'repeat from frame': 7},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (27,27,28,28,29,30,30,31), 'speed': 2,
                     'sound': None, 'sound at frames': (3,), 'repeat from frame': 7},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (27,27,28,28,29,30,30,31), 'speed': 2,
                     'sound': None, 'sound at frames': (3,), 'repeat from frame': 7},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (27,27,28,28,29,30,30,31), 'speed': 2,
                     'sound': None, 'sound at frames': (3,), 'repeat from frame': 7},
        },
        'exhausted': {
            'right': {'repeat': True, 'interruptable': True, 'sequence': (42,43), 'speed': 10,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (42,43), 'speed': 10,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (42,43), 'speed': 10,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (42,43), 'speed': 10,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
        },
        'stay still': {
            'right': {'repeat': True, 'interruptable': True, 'sequence': (1,1,1,1,1,1,2,2,2,2,2,2,2), 'speed': 20,
                       'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (1,1,1,1,1,1,2,2,2,2,2,2,2), 'speed': 20,
                       'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (3,), 'speed': 9,
                          'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (0,), 'speed': 9,
                            'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
        },
        'walk': {
            # 'right': {'repeat': True, 'interruptable': True, 'sequence': (17, ), 'speed': 1,
            #           'sound': 'step', 'sound at frames': (1, 4), 'repeat from frame': 0},
            'right': {'repeat': True, 'interruptable': True, 'sequence': (17,18,19,20,21,22,23,24,25,26,14,15,16), 'speed': 1,
                      'sound': 'step', 'sound at frames': (1, 4), 'repeat from frame': 0},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (17,18,19,20,21,22,23,24,25,26,14,15,16), 'speed': 1,
                      'sound': 'step', 'sound at frames': (1, 4), 'repeat from frame': 0},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (10, 11,), 'speed': 9,
                          'sound': 'step', 'sound at frames': (1,), 'repeat from frame': 0},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (8, 9), 'speed': 9,
                        'sound': 'step', 'sound at frames': (1,), 'repeat from frame': 0},
        },
        # 'stay still up': {},
        # 'stay still down': {},
    },
    # Animations for big sprites from file 'jake.png':
    # 'animations': {
    #     'firearm attack': {'repeat': False, 'interruptable': False, 'sequence': (12, 12, 13, 13, 13, 13, 13), 'speed': 1,
    #                        'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
    #     'shotgun attack': {'repeat': False, 'interruptable': False, 'sequence': (14, 14, 15, 15, 15, 15, 15, 15), 'speed': 1,
    #                        'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
    #     'melee attack': {'repeat': False, 'interruptable': False, 'sequence': (12, 12, 12, 12, 12, 12, 12), 'speed': 1,
    #                      'sound': 'swing', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'get hurt': {'repeat': False, 'interruptable': False, 'sequence': (17, 17, 18, 18, 18,), 'speed': 5,
    #                  'sound': 'jake groan', 'sound at frames': (3,), 'repeat from frame': 0},
    #     'lay down': {'repeat': True, 'interruptable': True, 'sequence': (18, 18, 19, 19, 19, 98, 98, 99, 99, 99, 99, 99, 99,), 'speed': 20,
    #                  'sound': None, 'sound at frames': (3,), 'repeat from frame': 5},
    #     'stay still': {'repeat': True, 'interruptable': True, 'sequence': (10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11), 'speed': 20,
    #                    'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    #     'walk': {'repeat': True, 'interruptable': True, 'sequence': (0, 1, 2, 3, 4, 5), 'speed': 5,
    #                   'sound': 'step', 'sound at frames': (1, 4), 'repeat from frame': 0},
    #     'down walk': {'repeat': True, 'interruptable': True, 'sequence': (8, 9), 'speed': 9,
    #                   'sound': 'step', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'up walk': {'repeat': True, 'interruptable': True, 'sequence': (6, 7), 'speed': 9,
    #                 'sound': 'step', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'stay still up': {'repeat': True, 'interruptable': True, 'sequence': (6,), 'speed': 9,
    #                       'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    #     'stay still down': {'repeat': True, 'interruptable': True, 'sequence': (8,), 'speed': 9,
    #                         'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    # },
    'thinking type': '',
    'AI controlled': False
}

player_jane = {
    'name': 'Jane',
    'body state': {
        'regeneration ability': 0,
        'marksmanship': 20,  # The higher -- the better
        'blood volume': 4500,
        'max blood volume': 4500,
        'blood volume replenish': 0.0005,
        'bleeding reduce': 0.001,  #
        'bleeding resistance': 0,  # Reduce bleeding, in percents.
        'weight': 50,  # Kilos.
        'reflexes': 250,  # minimal threshold of event speed which creature able to notice (in ms)
        'default reflexes': 250,
        'pain resistance': 0,  # Reduce total pain level, in percents.
        'max stamina': 100,
        'max stamina default': 100,
        'stamina replenish': 1,
        'max fatigue': 100,
        'consciousness replenish': 10,
        'max consciousness': 1000,
        'consciousness threshold': 10,
        'luck': 5,
        'strength': 5
    },
    'action points': 70,
    'reflexes': randint(200, 210),
    'uses light source': True,
    'items': (kitchen_knife,pistol_9mm,shotgun),
    'avatar': 'Jane',
    'animations': {
        'firearm attack': {'repeat': False, 'interruptable': False, 'sequence': (4, 4, 5, 5, 4, 4, 4, 4, 4), 'speed': 1,
                           'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
        'shotgun attack': {'repeat': False, 'interruptable': False, 'sequence': (4, 4, 5, 5, 4, 4, 4, 4, 4), 'speed': 1,
                           'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
        'melee attack': {'repeat': False, 'interruptable': False, 'sequence': (4, 4, 5, 5, 4, 4, 4, 4, 4), 'speed': 1,
                         'sound': 'swing', 'sound at frames': (1,), 'repeat from frame': 0},
        'get hurt': {'repeat': False, 'interruptable': False, 'sequence': (12, 13, 12, 13, 12, 13, 12, 13), 'speed': 2,
                     'sound': 'jake groan', 'sound at frames': (1,), 'repeat from frame': 0},
        'be dead': {'repeat': True, 'interruptable': True, 'sequence': (40,), 'speed': 1,
                    'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
        'head explode': {'repeat': True, 'interruptable': True, 'sequence': (34, 35, 36, 37, 38, 39, 40), 'speed': 1,
                         'sound': None, 'sound at frames': (0,), 'repeat from frame': 6},
        'lay down': {'repeat': True, 'interruptable': True, 'sequence': (27, 27, 28, 28, 29, 30, 30, 31), 'speed': 20,
                     'sound': None, 'sound at frames': (3,), 'repeat from frame': 7},
        'exhausted': {'repeat': True, 'interruptable': True, 'sequence': (42, 43), 'speed': 4,
                      'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
        'stay still': {'repeat': True, 'interruptable': True, 'sequence': (1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2), 'speed': 20,
                       'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
        'walk': {'repeat': True, 'interruptable': True, 'sequence': (17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 14, 15, 16), 'speed': 1,
                      'sound': 'step', 'sound at frames': (1, 4), 'repeat from frame': 0},
        'down walk': {'repeat': True, 'interruptable': True, 'sequence': (10, 11,), 'speed': 9,
                      'sound': 'step', 'sound at frames': (1,), 'repeat from frame': 0},
        'up walk': {'repeat': True, 'interruptable': True, 'sequence': (8, 9), 'speed': 9,
                    'sound': 'step', 'sound at frames': (1,), 'repeat from frame': 0},
        'stay still up': {'repeat': True, 'interruptable': True, 'sequence': (3,), 'speed': 9,
                          'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
        'stay still down': {'repeat': True, 'interruptable': True, 'sequence': (0,), 'speed': 9,
                            'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    },
    # Aniamtions for big file jane.png
    # 'animations': {
    #     'shotgun attack': {'repeat': False, 'interruptable': False, 'sequence': ( 4, 3, 3, 1, 1, 1), 'speed': 1,
    #                        'sound': 'gunshot', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'firearm attack': {'repeat': False, 'interruptable': False, 'sequence': ( 4, 3, 3, 1, 1, 1), 'speed': 1,
    #                        'sound': 'gunshot', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'melee attack': {'repeat': False, 'interruptable': False, 'sequence': (0,0,0,3,3,3,3,3,3), 'speed': 1,
    #                      'sound': 'swing', 'sound at frames': (3,), 'repeat from frame': 0},
    #     'get hurt': {'repeat': False, 'interruptable': False, 'sequence': (10,1,11,1,10,1,11,1,10,1,11,1,10,1,11), 'speed': 1,
    #                  'sound': 'jane groan', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'lay down': {'repeat': True, 'interruptable': True, 'sequence': (12,12,13,13,13,13,13), 'speed': 23,
    #                  'sound': None, 'sound at frames': (1,), 'repeat from frame': 0},
    #     'stay still': {'repeat': True, 'interruptable': True, 'sequence': (2, ), 'speed': 20,
    #                    'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    #     'walk': {'repeat': True, 'interruptable': True, 'sequence': (0,1,2,3,4,5), 'speed': 3,
    #                   'sound': 'step', 'sound at frames': (1, 4), 'repeat from frame': 0},
    #     'down walk': {'repeat': True, 'interruptable': True, 'sequence': (8,9), 'speed': 9,
    #                   'sound': 'step', 'sound at frames': (1, ), 'repeat from frame': 0},
    #     'up walk': {'repeat': True, 'interruptable': True, 'sequence': (6,7), 'speed': 9,
    #                 'sound': 'step', 'sound at frames': (1, ), 'repeat from frame': 0},
    #     'stay still up': {'repeat': True, 'interruptable': True, 'sequence': (6,), 'speed': 9,
    #                       'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    #     'stay still down': {'repeat': True, 'interruptable': True, 'sequence': (8,), 'speed': 9,
    #                         'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    # },
    'AI controlled': False
}

demon_female_1 = {
    'name': 'demon Hildegarda',
    'body state': {
        'viewing range': 600,
        'regeneration ability': 0,
        'marksmanship': 10,  # The higher -- the better
        'blood volume': 5000,
        'max blood volume': 5000,
        'blood volume replenish': 0.1,
        'bleeding reduce': 0.1,  #
        'bleeding resistance': 1,  # Reduce bleeding, in percents.
        'weight': 80,  # Kilos.
        'reflexes': 250,  # minimal threshold of event speed which creature able to notice (in ms)
        'default reflexes': 250,
        'pain resistance': 1,  # Change total pain level by multiplying total pain level to this number.
                               # Below 1 is reducing, above 1 is increasing. The smaller the number, the stronger pain resistance.
                               # Zero means total pain resist.
        'max stamina': 100,
        'max stamina default': 100,
        'stamina replenish': 1,
        'max fatigue': 100,
        'consciousness replenish': 10,
        'max consciousness': 1000,
        'consciousness threshold': 10,
        'luck': 5,
        'strength': 5
    },
    'max speed': .4,
    'body': {
        'head': {
            'hardness': 4,
            'consistency': 10,
            'consistency default': 10
        },
    },
    'action points': 50,
    'avatar': 'demon Hildegarda',
    # 'avatar': 'phantom',
    # 'avatar': 'zombie2',
    'reflexes': randint(240, 250),
    'uses light source': False,
    'items': (kitchen_knife,pistol_9mm, brass_garden_key, tiny_heal_vial, painkillers),
    # 'items': (pistol_9mm, brass_garden_key, tiny_heal_vial, painkillers),
    'animations': {
        'firearm attack': {
            'right': {'repeat': False, 'interruptable': False, 'sequence': (4, 4, 5, 5, 4, 4, 4, 4, 4), 'speed': 1,
                                     'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
            'left': {'repeat': False, 'interruptable': False, 'sequence': (4, 4, 5, 5, 4, 4, 4, 4, 4), 'speed': 1,
                                    'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
            'up': {'repeat': False, 'interruptable': False, 'sequence': (7, 7, 7, 7, 7, 7, 7, 7, 7), 'speed': 1,
                                  'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
            'down': {'repeat': False, 'interruptable': False, 'sequence': (6, 6, 6, 6, 6, 6, 6, 6, 6), 'speed': 1,
                                    'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
        },
        'shotgun attack': {
            'right': {'repeat': False, 'interruptable': False, 'sequence': (4, 4, 5, 5, 4, 4, 4, 4, 4), 'speed': 1,
                      'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
            'left': {'repeat': False, 'interruptable': False, 'sequence': (4, 4, 5, 5, 4, 4, 4, 4, 4), 'speed': 1,
                     'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
            'up': {'repeat': False, 'interruptable': False, 'sequence': (7, 7, 7, 7, 7, 7, 7, 7, 7), 'speed': 1,
                   'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
            'down': {'repeat': False, 'interruptable': False, 'sequence': (6, 6, 6, 6, 6, 6, 6, 6, 6), 'speed': 1,
                     'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
        },
        'melee attack': {
            'right': {'repeat': False, 'interruptable': False, 'sequence': (32, 33, 33, 33), 'speed': 1,
                      'sound': 'swing', 'sound at frames': (1,), 'repeat from frame': 0},

            'left': {'repeat': False, 'interruptable': False, 'sequence': (32, 33, 33, 33), 'speed': 1,
                     'sound': 'swing', 'sound at frames': (1,), 'repeat from frame': 0},
            'up': {'repeat': False, 'interruptable': False, 'sequence': (7, 7, 7, 7), 'speed': 1,
                   'sound': 'swing', 'sound at frames': (1,), 'repeat from frame': 0},
            'down': {'repeat': False, 'interruptable': False, 'sequence': (6, 6, 6, 6), 'speed': 1,
                     'sound': 'swing', 'sound at frames': (1,), 'repeat from frame': 0},
        },
        'get hurt': {
            'right': {'repeat': False, 'interruptable': False, 'sequence': (12, 13, 12, 13, 12, 13, 12, 13), 'speed': 2,
                      'sound': 'jake groan', 'sound at frames': (1,), 'repeat from frame': 0},
            'left': {'repeat': False, 'interruptable': False, 'sequence': (12, 13, 12, 13, 12, 13, 12, 13), 'speed': 2,
                     'sound': 'jake groan', 'sound at frames': (1,), 'repeat from frame': 0},
            'up': {'repeat': False, 'interruptable': False, 'sequence': (7, 13, 7, 13, 7, 13, 7, 13), 'speed': 2,
                   'sound': 'jake groan', 'sound at frames': (1,), 'repeat from frame': 0},
            'down': {'repeat': False, 'interruptable': False, 'sequence': (27, 13, 27, 13, 27, 13, 27, 13), 'speed': 2,
                     'sound': 'jake groan', 'sound at frames': (1,), 'repeat from frame': 0},
        },
        'be dead': {
            'right': {'repeat': True, 'interruptable': True, 'sequence': (40,), 'speed': 1,
                      'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (40,), 'speed': 1,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (40,), 'speed': 1,
                   'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (40,), 'speed': 1,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
        },
        'head explode': {
            'right': {'repeat': True, 'interruptable': True, 'sequence': (34, 35, 36, 37, 38, 39, 40), 'speed': 1,
                      'sound': None, 'sound at frames': (0,), 'repeat from frame': 6},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (34, 35, 36, 37, 38, 39, 40), 'speed': 1,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 6},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (34, 35, 36, 37, 38, 39, 40), 'speed': 1,
                   'sound': None, 'sound at frames': (0,), 'repeat from frame': 6},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (34, 35, 36, 37, 38, 39, 40), 'speed': 1,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 6},
        },
        'lay down': {
            'right': {'repeat': True, 'interruptable': True, 'sequence': (27, 27, 28, 28, 29, 30, 30, 31), 'speed': 2,
                      'sound': None, 'sound at frames': (3,), 'repeat from frame': 7},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (27, 27, 28, 28, 29, 30, 30, 31), 'speed': 2,
                     'sound': None, 'sound at frames': (3,), 'repeat from frame': 7},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (27, 27, 28, 28, 29, 30, 30, 31), 'speed': 2,
                   'sound': None, 'sound at frames': (3,), 'repeat from frame': 7},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (27, 27, 28, 28, 29, 30, 30, 31), 'speed': 2,
                     'sound': None, 'sound at frames': (3,), 'repeat from frame': 7},
        },
        'exhausted': {
            'right': {'repeat': True, 'interruptable': True, 'sequence': (42, 43), 'speed': 10,
                      'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (42, 43), 'speed': 10,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (42, 43), 'speed': 10,
                   'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (42, 43), 'speed': 10,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
        },
        'stay still': {
            'right': {'repeat': True, 'interruptable': True, 'sequence': (1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2), 'speed': 20,
                      'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2), 'speed': 20,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (3,), 'speed': 9,
                   'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (0,), 'speed': 9,
                     'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
        },
        'walk': {
            'right': {'repeat': True, 'interruptable': True, 'sequence': (17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 14, 15, 16), 'speed': 2,
                      'sound': 'step', 'sound at frames': (1, 4), 'repeat from frame': 0},
            'left': {'repeat': True, 'interruptable': True, 'sequence': (17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 14, 15, 16), 'speed': 2,
                     'sound': 'step', 'sound at frames': (1, 4), 'repeat from frame': 0},
            'down': {'repeat': True, 'interruptable': True, 'sequence': (10, 11,), 'speed': 9,
                     'sound': 'step', 'sound at frames': (1,), 'repeat from frame': 0},
            'up': {'repeat': True, 'interruptable': True, 'sequence': (8, 9), 'speed': 9,
                   'sound': 'step', 'sound at frames': (1,), 'repeat from frame': 0},
        },
    },
    # 'animations': {
    #     'firearm attack': {'repeat': False, 'interruptable': False, 'sequence': (4, 4, 5, 5, 4, 4, 4, 4, 4), 'speed': 1,
    #                        'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
    #     'shotgun attack': {'repeat': False, 'interruptable': False, 'sequence': (4, 4, 5, 5, 4, 4, 4, 4, 4), 'speed': 1,
    #                        'sound': 'gunshot', 'sound at frames': (2,), 'repeat from frame': 0},
    #     'melee attack': {'repeat': False, 'interruptable': False, 'sequence': (32, 33, 33, 33), 'speed': 1,
    #                      'sound': 'swing', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'get hurt': {'repeat': False, 'interruptable': False, 'sequence': (12, 13, 12, 13, 12, 13, 12, 13), 'speed': 1,
    #                  'sound': 'jake groan', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'be dead': {'repeat': True, 'interruptable': True, 'sequence': (40,), 'speed': 1,
    #                   'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    #     'head explode': {'repeat': True, 'interruptable': True, 'sequence': (34,35,36,37,38,39,40), 'speed': 1,
    #                       'sound': 'hula groan', 'sound at frames': (0,), 'repeat from frame': 6},
    #     'exhausted': {'repeat': True, 'interruptable': True, 'sequence': (42, 43), 'speed': 4,
    #                   'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    #     'lay down': {'repeat': True, 'interruptable': True, 'sequence': (27, 27, 28, 28, 29, 30, 30, 31), 'speed': 2,
    #                  'sound': None, 'sound at frames': (3,), 'repeat from frame': 7},
    #     'stay still': {'repeat': True, 'interruptable': True, 'sequence': (1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2), 'speed': 20,
    #                    'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    #     'walk': {'repeat': True, 'interruptable': True, 'sequence': (17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 14, 15, 16), 'speed': 1,
    #                   'sound': 'step', 'sound at frames': (1, 4), 'repeat from frame': 0},
    #     'down walk': {'repeat': True, 'interruptable': True, 'sequence': (10, 11,), 'speed': 9,
    #                   'sound': 'step', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'up walk': {'repeat': True, 'interruptable': True, 'sequence': (8, 9), 'speed': 9,
    #                 'sound': 'step', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'stay still up': {'repeat': True, 'interruptable': True, 'sequence': (3,), 'speed': 9,
    #                       'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    #     'stay still down': {'repeat': True, 'interruptable': True, 'sequence': (0,), 'speed': 9,
    #                         'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    # },
    # Animations for big sprites from file 'demon_female_1.png':
    # 'animations': {
    #     # 'round sign': {'description': 'round', 'sequence': (0, 1), 'speed': 20},
    #     'firearm attack': {'repeat': False, 'interruptable': False, 'sequence': (2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 1, 1, 1), 'speed': 1,
    #                        'sound': 'swing', 'sound at frames': (2,), 'repeat from frame': 0},
    #     'melee attack': {'repeat': False, 'interruptable': False, 'sequence': (
    #     0, 2, 3, 4, 4, 4, 4, 4, 3, 3, 1, 1, ), 'speed': 1,
    #                      'sound': 'swing', 'sound at frames': (3,), 'repeat from frame': 0},
    #     'get hurt': {'repeat': False, 'interruptable': False, 'sequence': (5,6,6,7,7,8,8,7), 'speed': 1,
    #                  'sound': 'hula groan', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'lay down': {'repeat': True, 'interruptable': True, 'sequence': (7,8,99,), 'speed': 1,
    #                  'sound': None, 'sound at frames': (1,), 'repeat from frame': 2},
    #     'stay still': {'repeat': True, 'interruptable': True, 'sequence': (1, 1, 2, 2), 'speed': 20,
    #                    'sound': None, 'sound at frames': (2,), 'repeat from frame': 0},
    #     'walk': {'repeat': True, 'interruptable': True, 'sequence': (0, 1,3,1), 'speed': 15,
    #                   'sound': 'step', 'sound at frames': (1,), 'repeat from frame': 0},
    #     'down walk': {'repeat': True, 'interruptable': True, 'sequence': (0, ), 'speed': 9,
    #                   'sound': 'step', 'sound at frames': (0,), 'repeat from frame': 0},
    #     'up walk': {'repeat': True, 'interruptable': True, 'sequence': (3, ), 'speed': 9,
    #                 'sound': 'step', 'sound at frames': (0,), 'repeat from frame': 0},
    #     'stay still up': {'repeat': True, 'interruptable': True, 'sequence': (3,), 'speed': 9,
    #                       'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    #     'stay still down': {'repeat': True, 'interruptable': True, 'sequence': (0,), 'speed': 9,
    #                         'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    # },
    'thinking type': 'demon 1',
    'AI controlled': True
}

demon_female_2 = {
    'name': 'demon Hula',
    'body state': {
        'regeneration ability': 100,
        'blood volume': 15000,
        'max blood volume': 15000,
        'blood volume replenish': 1,
        'bleeding reduce': 2,  #
        'bleeding resistance': 0,  # Reduce bleeding, in percents.
        'weight': 90,  # Kilos.
        'reflexes': 250,  # minimal threshold of event speed which creature able to notice (in ms)
        'default reflexes': 250,
        'pain resistance': 0,  # Reduce total pain level, in percents.
        'max stamina': 100,
        'max stamina default': 100,
        'stamina replenish': 1,
        'max fatigue': 100,
        'consciousness replenish': 10,
        'max consciousness': 1000,
        'consciousness threshold': 10,
        'luck': 5,
        'strength': 150
    },
    'action points': 500,
    'avatar': 'demon Hula',
    'reflexes': randint(140, 150),
    'uses light source': False,
    'items': (kitchen_knife, knuckles),
    'animations': {
        # 'round sign': {'description': 'round', 'sequence': (0, 1), 'speed': 20},
        'firearm attack': {'repeat': False, 'interruptable': False, 'sequence': (
            2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 1, 1, 1), 'speed': 1,
                           'sound': 'swing', 'sound at frames': (2,), 'repeat from frame': 0},
        'melee attack': {'repeat': False, 'interruptable': False, 'sequence': (
        0, 0, 2, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1), 'speed': 1,
                         'sound': 'swing', 'sound at frames': (4,), 'repeat from frame': 0},
        'get hurt': {'repeat': False, 'interruptable': False, 'sequence': (5,5,5,6,6,6,7,7,7,7,7,7), 'speed': 1,
                     'sound': 'hula groan', 'sound at frames': (1,), 'repeat from frame': 0},
        'lay down': {'repeat': True, 'interruptable': True, 'sequence': (99,), 'speed': 23,
                     'sound': None, 'sound at frames': (1,), 'repeat from frame': 0},
        'stay still': {'repeat': True, 'interruptable': True, 'sequence': (1, 1, 2, 2), 'speed': 20,
                       'sound': None, 'sound at frames': (2,), 'repeat from frame': 0},
        'walk': {'repeat': True, 'interruptable': True, 'sequence': (0, 1,3,1), 'speed': 15,
                      'sound': 'step', 'sound at frames': (0,), 'repeat from frame': 0},
        'down walk': {'repeat': True, 'interruptable': True, 'sequence': (0, ), 'speed': 9,
                      'sound': 'step', 'sound at frames': (0,), 'repeat from frame': 0},
        'up walk': {'repeat': True, 'interruptable': True, 'sequence': (3, ), 'speed': 9,
                    'sound': 'step', 'sound at frames': (0,), 'repeat from frame': 0},
        'stay still up': {'repeat': True, 'interruptable': True, 'sequence': (3,), 'speed': 9,
                          'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
        'stay still down': {'repeat': True, 'interruptable': True, 'sequence': (0,), 'speed': 9,
                            'sound': None, 'sound at frames': (0,), 'repeat from frame': 0},
    },
    'AI controlled': True
}

zombie_male_zak = {
    'name': 'ZAK',
    'action points': 8,
    'avatar': 'phantom',
    # 'avatar': 'phantom',
    # 'avatar': 'zombie2',
    'reflexes': randint(100, 150),
    'uses light source': False,
    'items': (claw, tiny_heal_vial),
    'animations': {
        'firearm attack': {'repeat': False, 'interruptable': False, 'sequence': (1, ), 'speed': 1},
        'melee attack': {'repeat': False, 'interruptable': False, 'sequence': (3,), 'speed': 1},
        'get hurt': {'repeat': False, 'interruptable': False, 'sequence': (1,4,1,4,1,4,1,4), 'speed': 1},
        'stay still': {'repeat': True, 'interruptable': True, 'sequence': (1,), 'speed': 20},
        'walk': {'repeat': True, 'interruptable': True, 'sequence': (0, 1, 2, 3, 4), 'speed': 5},
        'down walk': {'repeat': True, 'interruptable': True, 'sequence': (1,), 'speed': 9},
        'up walk': {'repeat': True, 'interruptable': True, 'sequence': (2,), 'speed': 9},
        'stay still down': {'repeat': True, 'interruptable': True, 'sequence': (1,), 'speed': 9},
        'stay still up': {'repeat': True, 'interruptable': True, 'sequence': (2,), 'speed': 9},
        # # 'round sign': {'description': 'round', 'sequence': (0, 1), 'speed': 5},
        # 'stay still': {'description': 'walk', 'sequence': (0,), 'speed': 30},
        # 'walk': {'description': 'walk', 'sequence': (0, 1, 2, 3, 4), 'speed': 4},
        # 'up walk': {'description': 'up walk', 'sequence': (0, 1), 'speed': 9},
        # 'down walk': {'description': 'down walk', 'sequence': (0, 1), 'speed': 9},
        # 'stay still up': {'description': 'up walk', 'sequence': (0,), 'speed': 9},
        # 'stay still down': {'description': 'down walk', 'sequence': (0,), 'speed': 9},
    },
    'AI controlled': True
}

player_dude = {
    'name': 'Mark de Casques',
    'action points': 4,
    'reflexes': randint(100, 150),
    'uses light source': False,
    'items': (fist, kitchen_knife, claw, pistol_9mm, shotgun, shotgun_ammo, pistol_9mm_ammo, tiny_heal_vial, brass_garden_key, flashlight),
    'avatar': 'Mark de Casques',
    'animations': {
        # 'round sign': {'description': 'round', 'sequence': (0, 1), 'speed': 55},
        'stay still': {'description': 'walk', 'sequence': (5, ), 'speed': 30},
        'walk': {'description': 'walk', 'sequence': (0,1,2,3,4,5,6,7,8,9,10,11), 'speed': 3},
        'up walk': {'description': 'up walk', 'sequence': (0,1,2,3,4,5,6,7,8,9,10,11), 'speed': 3},
        'down walk': {'description': 'down walk', 'sequence': (0,1,2,3,4,5,6,7,8,9,10,11), 'speed': 3},
        'stay still up': {'description': 'up walk', 'sequence': (0,), 'speed': 9},
        'stay still down': {'description': 'down walk', 'sequence': (0,), 'speed': 9},
    },
    'AI controlled': False
}

all_hostiles = {
    zombie_male_zak['name']: zombie_male_zak,
    demon_female_1['name']: demon_female_1,
    demon_female_2['name']: demon_female_2
}

all_players = {
    'Jane': player_jane,
    'Johnny Badge': player_jake,
    'Mark de Casques': player_dude
}
# moving_crate = {
#     'name': 'crate',
#     'description': 'furniture',
#     'avatar': 'obstacle',
#     'reflexes': 0,
#     'uses light source': False,
#     'items': None,
#     'animations': {
#         'stay still': {'description': 'metal crate #1', 'sequence': (0, ), 'speed': 5},
#         'walk': {'description': 'metal crate #1', 'sequence': (0, ), 'speed': 4},
#         'up walk': {'description': 'metal crate #1', 'sequence': (0, ), 'speed': 9},
#         'down walk': {'description': 'metal crate #1', 'sequence': (0, ), 'speed': 9},
#     },
#     # 'AI controlled': False
# }