from constants import *
locations = {
    
    'luxuryelevatorroom':
        {
            'music': 'music/ambient_1.mp3',
            'description': 'apartment #1',
            'size': (500, 500),
            'hostiles': {
              },
            'demolishers': {
                'dem rectangles': (
                  ), # DEMOLISHERS RECTANGLE SECTION END
            },
            'obstacles': {
                'obs rectangles': (
                ((-100, 450), (700, 50), 2),
                ((0, 0), (500, 50), 3),
                ((450, 50), (50, 200), 4),
                ((0, 50), (50, 200), 5),
                ((-100, 250), (50, 200), 6),
                ((-100, 200), (100, 50), 7),
                ((500, 200), (100, 50), 8),
                ((550, 250), (50, 200), 9),
                  ), # OBSTACLE RECTANGLES SECTION END
                'settings': {
                    6: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': True,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': True,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'luxuryhall', 'xy': (1900.0, 300.0)},
                  },
                  } # OBSTACLE SETTINGS SECTION END
              },
            'items': {},
    },
    'luxuryhall':
        {
            'music': 'music/ambient_1.mp3',
            'description': 'apartment #1',
            'size': (2000, 500),
            'hostiles': {
              },
            'demolishers': {
                'dem rectangles': (
                  ), # DEMOLISHERS RECTANGLE SECTION END
            },
            'obstacles': {
                'obs rectangles': (
                ((1950, 0), (50, 250), 2),  #2
                ((0, 0), (50, 250), 3),  #3
                ((50, 0), (1900, 50), 4),  #4
                ((2050, 250), (50, 200), 7),  #7
                ((2000, 200), (100, 50), 8),  #8
                ((-100, 200), (100, 50), 9),  #9
                ((-100, 250), (50, 200), 10),  #10
                ((300, 400), (50, 50), 11),  #11
                ((350, 350), (100, 100), 12),  #12
                ((400, 250), (100, 100), 13),  #13
                ((450, 350), (100, 100), 14),  #14
                ((500, 250), (100, 100), 15),  #15
                ((550, 350), (100, 100), 16),  #16
                ((500, 200), (50, 50), 17),  #17
                ((450, 100), (50, 150), 18),  #18
                ((350, 50), (200, 50), 19),  #19
                ((550, 150), (100, 100), 20),  #20
                ((-100, 450), (400, 50), 21),  #21
                ((300, 450), (400, 50), 25),  #25
                ((700, 450), (1400, 50), 26),  #26
                ((250, 100), (50, 350), 27),  #27
                ((750, 150), (100, 300), 28),  #28
                  ), # OBSTACLE RECTANGLES SECTION END
                'settings': {
                    10: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': True,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': True,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'stairway', 'xy': (1400.0, 300.0)},
                  },
                    16: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': True,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': True,
                        'gravity affected': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    15: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': True,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': True,
                        'gravity affected': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    14: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': True,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': True,
                        'gravity affected': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    12: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': True,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': True,
                        'gravity affected': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    11: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': True,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': True,
                        'gravity affected': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    13: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': True,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': True,
                        'gravity affected': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    18: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': True,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': True,
                        'gravity affected': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    17: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': True,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': True,
                        'gravity affected': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    19: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': True,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': True,
                        'gravity affected': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    20: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': True,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': True,
                        'gravity affected': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    27: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': True,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': True,
                        'trigger description': {'make active': [(25, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    25: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: [('switch passability', 0), ('wait', 0), ('die', 0)]},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    7: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'ghost': False,
                        'actors pass through': True,
                        'actors may grab': False,
                        'speed': 0.2,
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'teleport': True,
                        'teleport description': {'new location': 'luxuryelevatorroom', 'xy': (50.0, 300.0)},
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'active': False,
                        'actions': {0: []},
                  },
                    28: {
                        'sprite elevated': False,
                        'sprite': 0,
                        'force render': False,
                        'ghost': False,
                        'actors pass through': False,
                        'actors may grab': False,
                        'speed': 0.2,
                        'collideable': True,
                        'gravity affected': True,
                        'invisible': True,
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'item': False,
                        'item name': {'name': ''},
                        'active': False,
                        'actions': {0: []},
                  },
                  } # OBSTACLE SETTINGS SECTION END
              },
            'items': {},
    },
    'stairway':
        {
            'music': 'music/ambient_1.mp3',
            'description': 'apartment #1',
            'size': (1500, 5000),
            'hostiles': {
              },
            'demolishers': {
                'dem rectangles': (
                  ), # DEMOLISHERS RECTANGLE SECTION END
            },
            'obstacles': {
                'obs rectangles': (
                ((0, 4950), (1500, 50), 1),
                ((-100, 4750), (50, 200), 2),
                ((1450, 4750), (50, 200), 3),
                ((50, 4450), (450, 50), 6),
                ((50, 3950), (450, 50), 7),
                ((50, 3450), (450, 50), 9),
                ((1000, 3450), (450, 50), 14),
                ((1000, 3950), (450, 50), 15),
                ((1000, 4450), (450, 50), 16),
                ((0, 4450), (50, 300), 17),
                ((0, 4250), (50, 200), 18),
                ((0, 3950), (50, 300), 19),
                ((0, 3750), (50, 200), 20),
                ((0, 3450), (50, 300), 21),
                ((1450, 4450), (50, 300), 22),
                ((1450, 4250), (50, 200), 23),
                ((1450, 3950), (50, 300), 24),
                ((1450, 3750), (50, 200), 25),
                ((1450, 3450), (50, 300), 26),
                ((0, 3250), (50, 200), 27),
                ((0, 2950), (50, 300), 28),
                ((50, 2950), (450, 50), 29),
                ((0, 2750), (50, 200), 30),
                ((0, 2450), (50, 300), 31),
                ((50, 2450), (450, 50), 32),
                ((0, 2250), (50, 200), 33),
                ((0, 1950), (50, 300), 34),
                ((50, 1950), (450, 50), 35),
                ((0, 1750), (50, 200), 36),
                ((0, 1450), (50, 300), 37),
                ((50, 1450), (450, 50), 38),
                ((0, 1250), (50, 200), 39),
                ((0, 950), (50, 300), 40),
                ((50, 950), (450, 50), 41),
                ((0, 750), (50, 200), 42),
                ((0, 450), (50, 300), 43),
                ((50, 450), (450, 50), 44),
                ((0, 250), (50, 200), 45),
                ((0, 0), (50, 250), 46),
                ((1450, 50), (50, 200), 48),
                ((1550, 250), (50, 200), 49),
                ((1000, 450), (450, 50), 50),
                ((1450, 450), (50, 300), 51),
                ((1450, 3250), (50, 200), 52),
                ((1000, 2950), (450, 50), 53),
                ((1450, 2950), (50, 300), 54),
                ((1000, 2450), (450, 50), 55),
                ((1450, 2450), (50, 300), 56),
                ((1450, 2750), (50, 200), 57),
                ((1000, 1950), (450, 50), 58),
                ((1450, 1950), (50, 300), 59),
                ((1450, 2250), (50, 200), 60),
                ((1000, 1450), (450, 50), 61),
                ((1450, 1450), (50, 300), 62),
                ((1450, 1750), (50, 200), 63),
                ((1000, 950), (450, 50), 64),
                ((1450, 750), (50, 200), 65),
                ((1450, 950), (50, 300), 66),
                ((1450, 1250), (50, 200), 68),
                ((-100, 4950), (100, 50), 69),
                ((-100, 4700), (100, 50), 70),
                ((500, 4450), (500, 50), 71),
                ((500, 3950), (500, 50), 72),
                ((500, 3450), (500, 50), 73),
                ((500, 2950), (500, 50), 74),
                ((500, 2450), (500, 50), 75),
                ((500, 1950), (500, 50), 76),
                ((500, 1450), (500, 50), 77),
                ((500, 950), (500, 50), 78),
                ((500, 450), (500, 50), 79),
                ((500, 4700), (500, 50), 80),
                ((500, 4200), (500, 50), 81),
                ((500, 3700), (500, 50), 82),
                ((500, 3200), (500, 50), 83),
                ((500, 2700), (500, 50), 84),
                ((500, 2200), (500, 50), 85),
                ((500, 1700), (500, 50), 86),
                ((500, 1200), (500, 50), 87),
                ((500, 700), (500, 50), 88),
                ((700, 0), (100, 50), 89),
                ((800, 0), (700, 50), 90),
                ((50, 0), (650, 50), 91),
                ((1500, 450), (100, 50), 92),
                ((1500, 200), (100, 50), 93),
                  ), # OBSTACLE RECTANGLES SECTION END
                'settings': {
                    2: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': True,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': True,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'hall', 'xy': (1900.0, 800.0)},
                  },
                    71: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    72: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    73: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    74: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    75: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    76: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    77: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    78: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    79: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    80: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    81: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    82: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    83: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    84: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    85: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    86: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    87: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    88: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': False,
                        'ghost': True,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': False,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    49: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': True,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': True,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'luxuryhall', 'xy': (50.0, 300.0)},
                  },
                  } # OBSTACLE SETTINGS SECTION END
              },
            'items': {},
    },
    'hall':
        {
            'music': 'music/ambient_1.mp3',
            'description': 'apartment #1',
            'size': (2000, 1000),
            'hostiles': {
              },
            'demolishers': {
                'dem rectangles': (
                  ), # DEMOLISHERS RECTANGLE SECTION END
            },
            'obstacles': {
                'obs rectangles': (
                ((0, 950), (2000, 50), 1),
                ((2050, 750), (50, 200), 2),
                ((-100, 750), (50, 200), 3),
                ((0, 0), (50, 750), 4),
                ((50, 0), (1950, 50), 5),
                ((1950, 50), (50, 700), 6),
                ((-100, 950), (100, 50), 7),
                ((-100, 700), (100, 50), 8),
                ((2000, 950), (100, 50), 9),
                ((2000, 700), (100, 50), 10),
                  ), # OBSTACLE RECTANGLES SECTION END
                'settings': {
                    3: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': True,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': True,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'entrance', 'xy': (1900.0, 2300.0)},
                  },
                    2: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': True,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': True,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'stairway', 'xy': (50.0, 4800.0)},
                  },
                  } # OBSTACLE SETTINGS SECTION END
              },
            'items': {},
    },
    'entrance':
        {
            'music': 'music/ambient_1.mp3',
            'description': 'apartment #1',
            'size': (2000, 2500),
            'hostiles': {
              },
            'demolishers': {
                'dem rectangles': (
                  ), # DEMOLISHERS RECTANGLE SECTION END
            },
            'obstacles': {
                'obs rectangles': (
                ((0, 2450), (2000, 50), 1),
                ((1850, 2200), (150, 50), 2),
                ((0, 0), (50, 2450), 3),
                ((1750, 0), (250, 50), 4),
                ((1950, 50), (50, 200), 5),
                ((1800, 450), (200, 50), 6),
                ((1750, 350), (50, 150), 7),
                ((1950, 500), (50, 250), 8),
                ((1950, 250), (50, 200), 9),
                ((1950, 750), (50, 200), 10),
                ((1800, 950), (200, 50), 11),
                ((1750, 850), (50, 150), 12),
                ((1950, 1000), (50, 250), 13),
                ((1950, 1250), (50, 200), 14),
                ((1800, 1450), (200, 50), 15),
                ((1750, 1350), (50, 150), 16),
                ((1950, 1500), (50, 700), 17),
                ((2050, 2250), (50, 200), 18),
                ((2000, 2450), (100, 50), 20),
                ((2000, 2200), (100, 50), 21),
                ((50, 0), (1700, 50), 22),
                  ), # OBSTACLE RECTANGLES SECTION END
                'settings': {
                    18: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'force render': False,
                        'invisible': True,
                        'ghost': False,
                        'speed': 0.2,
                        'actors may grab': False,
                        'actors pass through': True,
                        'active': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'hall', 'xy': (50.0, 800.0)},
                  },
                  } # OBSTACLE SETTINGS SECTION END
              },
            'items': {},
    },
}