from constants import *
locations = {
    
    'zxcv':
        {
            'music': 'music/ambient_1.mp3',
            'description': 'apartment #1',
            'size': (1920, 1000),
            'hostiles': {
              },
            'demolishers': {
                'dem rectangles': (
                  ), # DEMOLISHERS RECTANGLE SECTION END
            },
            'obstacles': {
                'obs rectangles': (
                ((0, 0), (350, 1000), 1),  #1
                ((350, 850), (1600, 150), 2),  #2
                ((1800, 0), (150, 850), 3),  #3
                ((350, 800), (1000, 50), 4),  #4
                ((1350, 750), (450, 50), 5),  #5
                ((1350, 800), (450, 50), 6),  #6
                  ), # OBSTACLE RECTANGLES SECTION END
                'settings': {
                    1: {
                        'sprite': 23,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'force render': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    2: {
                        'sprite': 23,
                        'sprite elevated': True,
                        'actors pass through': False,
                        'force render': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    3: {
                        'sprite': 23,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'force render': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    4: {
                        'sprite': 22,
                        'sprite elevated': True,
                        'actors pass through': False,
                        'force render': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    5: {
                        'sprite': 2,
                        'sprite elevated': True,
                        'actors pass through': False,
                        'force render': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    6: {
                        'sprite': 3,
                        'sprite elevated': True,
                        'actors pass through': False,
                        'force render': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                  } # OBSTACLE SETTINGS SECTION END
              },
            'items': {},
    },
    'qwe':
        {
            'music': 'music/ambient_1.mp3',
            'description': 'apartment #1',
            'size': (1920, 1000),
            'hostiles': {
              },
            'demolishers': {
                'dem rectangles': (
                  ), # DEMOLISHERS RECTANGLE SECTION END
            },
            'obstacles': {
                'obs rectangles': (
                ((0, 950), (1050, 50), 1),
                ((1250, 950), (700, 50), 2),
                ((1050, 850), (200, 100), 3),
                ((1000, 600), (50, 350), 4),
                ((1250, 600), (50, 350), 5),
                ((900, 650), (100, 300), 6),
                ((800, 700), (100, 250), 7),
                ((700, 750), (100, 200), 8),
                ((600, 800), (100, 150), 9),
                ((500, 850), (100, 100), 10),
                ((400, 900), (100, 50), 11),
                ((0, 0), (50, 750), 12),
                ((1900, 0), (50, 950), 13),
                ((50, 0), (1850, 50), 14),
                ((0, 750), (50, 200), 15),
                ((350, 925), (50, 25), 16),
                ((450, 875), (50, 25), 17),
                ((550, 825), (50, 25), 18),
                ((650, 775), (50, 25), 19),
                ((750, 725), (50, 25), 20),
                ((850, 675), (50, 25), 21),
                ((950, 625), (50, 25), 22),
                ((1825, 850), (75, 100), 23),
                ((1875, 725), (25, 125), 24),
                ((1775, 850), (50, 100), 25),
                ((1050, 950), (200, 50), 26),
                  ), # OBSTACLE RECTANGLES SECTION END
                'settings': {
                    15: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': True,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'cave', 'xy': (4850.0, 650.0)},
                  },
                    25: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': True,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: [('move', (0, 0)), ('wait', 0), ('stop', (0, 0))]},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': True,
                        'trigger description': {'make active': [(3, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    3: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'force render': True,
                        'ghost': False,
                        'speed': 1.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: [('move', (1050, 50)), ('wait', 100), ('stop', (0, 0))]},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'trigger': False,
                        'trigger description': {'make active': [3], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    26: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': True,
                        'force render': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'zxcv', 'xy': (1000.0, 0.0)},
                  },
                    23: {
                        'sprite': 27,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'force render': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    24: {
                        'sprite': 27,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'force render': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                  } # OBSTACLE SETTINGS SECTION END
              },
            'items': {},
    },
    'cave':
        {
            'music': 'music/ambient_1.mp3',
            'description': 'apartment #1',
            'size': (5000, 2000),
            'hostiles': {
              },
            'demolishers': {
                'dem rectangles': (
                  ), # DEMOLISHERS RECTANGLE SECTION END
            },
            'obstacles': {
                'obs rectangles': (
                ((0, 1950), (5000, 50), 10),
                ((0, 0), (50, 1700), 11),
                ((0, 1700), (50, 250), 12),
                ((4950, 800), (50, 1150), 13),
                ((4950, 0), (50, 550), 14),
                ((50, 0), (4900, 50), 15),
                ((650, 1700), (500, 50), 16),
                ((650, 1750), (500, 200), 17),
                ((50, 1200), (450, 50), 20),
                ((50, 1250), (100, 400), 22),
                ((150, 1250), (200, 250), 23),
                ((350, 1250), (100, 100), 24),
                ((150, 1500), (50, 50), 25),
                ((50, 1650), (50, 50), 26),
                ((750, 50), (2000, 750), 28),
                ((1000, 800), (1650, 250), 29),
                ((1750, 1050), (200, 500), 31),
                ((1950, 1050), (50, 250), 32),
                ((1200, 1050), (250, 100), 33),
                ((1300, 1150), (150, 250), 34),
                ((1350, 1400), (100, 150), 35),
                ((1750, 1500), (100, 200), 37),
                ((1450, 1050), (50, 250), 38),
                ((1200, 200), (850, 500), 39),
                ((1100, 300), (100, 300), 40),
                ((2050, 300), (100, 300), 41),
                ((1300, 700), (650, 50), 42),
                ((1300, 150), (650, 50), 43),
                ((1450, 750), (50, 250), 44),
                ((1700, 750), (50, 150), 45),
                ((2950, 800), (2000, 50), 46),
                ((2750, 800), (200, 50), 47),
                ((2750, 1100), (200, 50), 48),
                ((2750, 1400), (200, 50), 49),
                ((2750, 1700), (200, 50), 50),
                ((4950, 550), (50, 250), 51),
                  ), # OBSTACLE RECTANGLES SECTION END
                'settings': {
                    12: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': True,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'entrance', 'xy': (4850.0, 800.0)},
                  },
                    10: {
                        'sprite': 22,
                        'sprite elevated': True,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'entrance', 'xy': (4850.0, 750.0)},
                  },
                    11: {
                        'sprite': 18,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'entrance', 'xy': (4850.0, 750.0)},
                  },
                    13: {
                        'sprite': 18,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'entrance', 'xy': (4850.0, 750.0)},
                  },
                    14: {
                        'sprite': 18,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'entrance', 'xy': (4850.0, 750.0)},
                  },
                    15: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'entrance', 'xy': (4850.0, 750.0)},
                  },
                    16: {
                        'sprite': 17,
                        'sprite elevated': True,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'entrance', 'xy': (4850.0, 750.0)},
                  },
                    17: {
                        'sprite': 18,
                        'sprite elevated': True,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'entrance', 'xy': (4850.0, 750.0)},
                  },
                    20: {
                        'sprite': 17,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': True,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    22: {
                        'sprite': 23,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    23: {
                        'sprite': 23,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    24: {
                        'sprite': 23,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    25: {
                        'sprite': 23,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    26: {
                        'sprite': 23,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    31: {
                        'sprite': 22,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    32: {
                        'sprite': 22,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    35: {
                        'sprite': 22,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    34: {
                        'sprite': 22,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    33: {
                        'sprite': 22,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    29: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    28: {
                        'sprite': 23,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    37: {
                        'sprite': 22,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    38: {
                        'sprite': 22,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    39: {
                        'sprite': 11,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'cave', 'xy': (100.0, 1800.0)},
                  },
                    40: {
                        'sprite': 11,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'cave', 'xy': (100.0, 1800.0)},
                  },
                    41: {
                        'sprite': 11,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'cave', 'xy': (100.0, 1800.0)},
                  },
                    42: {
                        'sprite': 11,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'cave', 'xy': (100.0, 1800.0)},
                  },
                    43: {
                        'sprite': 11,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'cave', 'xy': (100.0, 1800.0)},
                  },
                    44: {
                        'sprite': 11,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'cave', 'xy': (100.0, 1800.0)},
                  },
                    45: {
                        'sprite': 11,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'cave', 'xy': (100.0, 1800.0)},
                  },
                    47: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': True,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'qwe', 'xy': (100.0, 800.0)},
                  },
                    48: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': True,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'qwe', 'xy': (100.0, 800.0)},
                  },
                    49: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': True,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'qwe', 'xy': (100.0, 800.0)},
                  },
                    50: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': False,
                        'ghost': True,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': False,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': 'qwe', 'xy': (100.0, 800.0)},
                  },
                    51: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': True,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'qwe', 'xy': (100.0, 800.0)},
                  },
                  } # OBSTACLE SETTINGS SECTION END
              },
            'items': {},
    },
    'entrance':
        {
            'music': 'music/ambient_1.mp3',
            'description': 'apartment #1',
            'size': (5000, 1000),
            'hostiles': {
            	(3650.0, 200.0): {
                    'name': 'demon 1',
                    'height': 190,
                    'width': 49,
                    'health': 100.0,
                    'max speed': 2,

              },
              },
            'demolishers': {
                'dem rectangles': (
                  ), # DEMOLISHERS RECTANGLE SECTION END
            },
            'obstacles': {
                'obs rectangles': (
                ((0, 950), (5000, 50), 17),
                ((4950, 550), (50, 400), 18),
                ((4950, 0), (50, 550), 19),
                ((0, 0), (50, 950), 20),
                ((600, 850), (450, 50), 59),
                ((600, 900), (450, 50), 62),
                ((1700, 850), (500, 50), 65),
                ((1700, 900), (500, 50), 66),
                ((1150, 750), (450, 50), 67),
                ((1150, 800), (450, 150), 68),
                ((1200, 300), (50, 450), 69),
                ((1500, 300), (50, 450), 70),
                ((1150, 0), (450, 300), 72),
                ((2300, 500), (600, 50), 73),
                ((2350, 550), (50, 400), 74),
                ((2800, 550), (50, 400), 75),
                ((1050, 100), (100, 100), 76),
                ((1600, 100), (100, 100), 77),
                ((50, 0), (1100, 25), 78),
                ((1600, 0), (3350, 25), 79),
                ((3450, 450), (550, 50), 80),
                ((3950, 0), (50, 450), 81),
                ((50, 850), (550, 50), 85),
                ((50, 900), (550, 50), 86),
                  ), # OBSTACLE RECTANGLES SECTION END
                'settings': {
                    69: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': True,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    70: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': True,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    74: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': True,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    75: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': True,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': False,
                        'teleport description': {'new location': '', 'xy': [0, 0]},
                  },
                    18: {
                        'sprite': 0,
                        'sprite elevated': False,
                        'actors pass through': True,
                        'ghost': False,
                        'speed': 0.2,
                        'active': False,
                        'actors may grab': False,
                        'actions': {0: []},
                        'collideable': False,
                        'gravity affected': False,
                        'invisible': True,
                        'trigger': False,
                        'trigger description': {'make active': [(0, 'self', 0)], 'disappear': False},
                        'teleport': True,
                        'teleport description': {'new location': 'cave', 'xy': (100.0, 1800.0)},
                  },
                  } # OBSTACLE SETTINGS SECTION END
              },
            'items': {},
    },
}